### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by xizqu** [DigiThinkIT/python-metrc#3]
* Python METRC version: latest
* Python version: 3.7
* Operating System: windows 10

### Description

I am testing this to integrate into our erp. I am getting a 401 error

### What I Did

 metrc = METRC('https://sandbox-api-ca.metrc.com', vendor_key={'xxxxx'}, user_key={'xxxxx'}, license_number={'123-ABC'})

>>> metrc.transfers('delivery').packages('states').get()

<Response [401]>

**Comment by vjFaLk** [comment]
First I've edited your issue to remove the keys. 

Second, the actual issue. Is that the licence you're using? You need to use one of the demo licence that you can get from the API.

**Comment by xizqu** [comment]
Thank you, i appreciate the edit! 

I am in the testing phase of metrc api right now. I have only been givin' a user key and a vendor test key? 

May i ask what your best contact info is? I would love to chat via email or over the phone. My current developer doesnt speak english well and is having a hard time understanding what to do. Maybe your team can help me out? 

EDIT: I was given some JSON files titled "XXX17-0000005_packageTags" the xxx side is a couple letters that i took out for obscurity reasons. I thought this might be a license number but im still getting the same error :/

**Comment by vjFaLk** [comment]
Have a look here, and check the "Facilities" endpoint to get licences. 

https://api-ca.metrc.com/Documentation/

You can email me at valmik@bloomstack.com 

You will find this useful as well -https://github.com/DigiThinkIT/metrc-insomnia

**Comment by xizqu** [comment]
Thank you! Email has been sent. I hope we can work together :)

**Comment by xizqu** [comment]
Hey, sorry to bother you again. We finally figured everything out. However, we have 6 sections on the test we cannot complete. It seems others are having this error too. 

Certain endpoints don't seem to be reading the json file. Endpoints: harvests/v1/chagegrowthphase
harvests/v1/createpackages
harvests/v1/removewaste
plants/v1/moveplants
plants/v1/manicureplants
plants/v1/harvestplants
plants/v1/moveplants

These endpoints give an error "item with same key has already been added". I even took out everything in the Json file and got the same error which lead me to believe it's not reading the file. 

Do you have a solution for this? Did your team also encounter this error?
