### ISSUE TITLE
Assistance with Metrc APIs

### ISSUE THREAD

**Issue by vonschnappi** [DigiThinkIT/python-metrc#4]
Hi,

Not an issue but there's no way to DM users on github.

Would you be willing to help me with a few questions about Metrc API?

Thanks!

**Comment by Alchez** [comment]
Hey @vonschnappi, you can either post the questions here or email them to support@bloomstack.com

Thanks for reaching out!

**Comment by vonschnappi** [comment]
Hi @Alchez!

Thanks for posting back. I finally made it with the help of Metrc support. 

Thanks again for being willing to help.
